api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    title: "David Mailer"
    description: "MicroService to send emails"
    version: '0.0.1'
    show_webby: false

    # Allow using plain IDs for JSON format
    allow_plain_identifiers: true
    enable_fos_user: false

    # Enable ReDoc.
    enable_re_doc: true

    # Enable the entrypoint.
    enable_entrypoint: true

    # Enable the docs.
    enable_docs: true

    eager_loading:
        force_eager: false

    graphql:
        enabled: false
        graphiql:
            enabled: false


        #    swagger:
        # The swagger api keys.
    #        api_keys: []

    collection:
        # The default order of results.
        order: 'ASC'

        # The name of the query parameter to order results.
        order_parameter_name: 'order'

        pagination:
            enabled: false

    # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'

    # The list of exceptions mapped to their HTTP status code.
    exception_to_status:
        # With a status code.
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400

        # Or with a constant defined in the 'Symfony\Component\HttpFoundation\Response' class.
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST

    # The list of enabled formats. The first one will be the default.
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    # The list of enabled error formats. The first one will be the default.
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
